// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDvJgeCk-l5o-kdRXry1ioyuZDijZ594',
    appId: '1:184847416349:web:c3c4c7f66fbfd243eb1af4',
    messagingSenderId: '184847416349',
    projectId: 'mindmate-87312',
    authDomain: 'mindmate-87312.firebaseapp.com',
    storageBucket: 'mindmate-87312.firebasestorage.app',
    measurementId: 'G-115PFHKYTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxhXrCQ7UloVnuJuz_GRWDFwMTbXgl4mk',
    appId: '1:184847416349:android:59abc3e27592300aeb1af4',
    messagingSenderId: '184847416349',
    projectId: 'mindmate-87312',
    storageBucket: 'mindmate-87312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWRXZCD2BNB2iHGTiqRy8wacK_tieVjSY',
    appId: '1:184847416349:ios:8d91bda4a29ff012eb1af4',
    messagingSenderId: '184847416349',
    projectId: 'mindmate-87312',
    storageBucket: 'mindmate-87312.firebasestorage.app',
    iosBundleId: 'com.example.mindmateCaregiver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWRXZCD2BNB2iHGTiqRy8wacK_tieVjSY',
    appId: '1:184847416349:ios:8d91bda4a29ff012eb1af4',
    messagingSenderId: '184847416349',
    projectId: 'mindmate-87312',
    storageBucket: 'mindmate-87312.firebasestorage.app',
    iosBundleId: 'com.example.mindmateCaregiver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcDvJgeCk-l5o-kdRXry1ioyuZDijZ594',
    appId: '1:184847416349:web:927b0dee213a8537eb1af4',
    messagingSenderId: '184847416349',
    projectId: 'mindmate-87312',
    authDomain: 'mindmate-87312.firebaseapp.com',
    storageBucket: 'mindmate-87312.firebasestorage.app',
    measurementId: 'G-9EK3RWFCJF',
  );
}
